---
- name: "[{{ service_name }}] Создаём секрет"
  vars:
    ansible_python_interpreter: /opt/ansible-venvs/docker/bin/python
    env_file: "{{ lookup('template', service_name ~ '/.env.j2') }}"
  community.docker.docker_secret:
    name: "{{ service_name }}.env"
    data: "{{ env_file | b64encode }}"
    labels:
      secret: "{{ env_file | hash('sha1') }}"
    data_is_b64: true
    state: present
# - name: Debug
#   vars:
#     env_file: "{{ lookup('template', service_name ~ '/.env.j2') }}"
#   debug:
#     msg: "{{ env_file }}"
